// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }


import "./globals.css"; // optional, if using global styles
import { ReactNode } from "react";
import ClientLayout from "./components/clientLayout";

// Import consul registration (will auto-register on server start)
if (typeof window === 'undefined') {
  require('../../lib/consul-register');
}

export const metadata = {
  title: "App Title",
  description: "App Description",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
         <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
